FROM node:18-alpine3.17

WORKDIR /app/frontend

EXPOSE 3000

RUN corepack prepare yarn@3.5.1 --activate

COPY .yarnrc.yml .
COPY ./packages/frontend/.env ./.env
COPY ./packages/frontend/package.json .
COPY ./packages/frontend .

RUN yarn


CMD ["yarn", "start"]